version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Paris
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: tailwindcss
    versions:
    - 1.9.6
  - dependency-name: node-sass
    versions:
    - 5.0.0
