name: "CI"

on:
    pull_request: ~
    push:
        branches:
            - master

env:
    fail-fast: true

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                  ${{ runner.os }}-yarn-

            - run: yarn install
            - run: yarn type-check
            - run: yarn lint
            - run: yarn test
            - run: yarn build
